/**
 * Scaffolding logic for create-keel (a codai project).
 *
 * Clones the template repository (without git history), replaces branding
 * placeholders, configures Capacitor, writes environment variables,
 * optionally creates a docker-compose.yml, installs dependencies, and
 * initializes a fresh git repository.
 *
 * The template's sails/ folder only contains installed.json (empty tracker)
 * and .gitkeep. Actual sail code is NOT copied — sails are installed
 * on-demand from the CLI package via `keel sail add <name>`.
 */

import {
  existsSync,
  readFileSync,
  writeFileSync,
  copyFileSync,
  mkdirSync,
  readdirSync,
  statSync,
  rmSync,
} from "node:fs";
import { join, resolve } from "node:path";
import { execSync } from "node:child_process";
import chalk from "chalk";
import ora from "ora";
import degit from "degit";
import type { ProjectConfig } from "./prompts.js";

// The GitHub repository to clone from. Update this to your actual repo.
const TEMPLATE_REPO = "Chafficui/keel";

/**
 * Recursively find all files matching a pattern in a directory tree.
 */
function findFiles(dir: string, pattern: RegExp, results: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    // Skip node_modules and .git
    if (entry === "node_modules" || entry === ".git") continue;
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      findFiles(fullPath, pattern, results);
    } else if (pattern.test(entry)) {
      results.push(fullPath);
    }
  }
  return results;
}

/**
 * Replace all occurrences of a string in a file.
 */
function replaceInFile(filePath: string, search: string, replacement: string): void {
  if (!existsSync(filePath)) return;
  const content = readFileSync(filePath, "utf-8");
  if (!content.includes(search)) return;
  writeFileSync(filePath, content.replaceAll(search, replacement), "utf-8");
}

/**
 * Replace all occurrences across multiple files found by pattern.
 */
function replaceInAllFiles(
  dir: string,
  pattern: RegExp,
  search: string,
  replacement: string
): void {
  const files = findFiles(dir, pattern);
  for (const file of files) {
    replaceInFile(file, search, replacement);
  }
}

/**
 * Run a shell command, returning true if successful.
 */
function run(cmd: string, cwd: string): boolean {
  try {
    execSync(cmd, { cwd, stdio: "pipe" });
    return true;
  } catch {
    return false;
  }
}

/**
 * Build the .env file contents from the collected configuration.
 */
function buildEnvContents(config: ProjectConfig): string {
  const lines: string[] = [
    "# -------------------------------------------------------------------",
    "# Environment variables",
    `# Generated by create-keel for project: ${config.projectName}`,
    "# -------------------------------------------------------------------",
    "",
    "# Database",
    `DATABASE_URL=${config.databaseUrl}`,
    "",
    "# Auth",
    `BETTER_AUTH_SECRET=${config.betterAuthSecret}`,
    "",
    "# Email (Resend)",
    `RESEND_API_KEY=${config.resendApiKey}`,
    `EMAIL_FROM=${config.emailFrom}`,
    "",
  ];

  if (config.storageSetup) {
    lines.push(
      "# Cloudflare R2 Storage",
      `R2_ACCOUNT_ID=${config.r2AccountId}`,
      `R2_ACCESS_KEY_ID=${config.r2AccessKeyId}`,
      `R2_SECRET_ACCESS_KEY=${config.r2SecretAccessKey}`,
      `R2_BUCKET_NAME=${config.r2BucketName}`,
      ""
    );
  }

  return lines.join("\n") + "\n";
}

/**
 * Create a docker-compose.yml for local PostgreSQL development.
 */
function createDockerCompose(targetDir: string): void {
  const dockerComposePath = join(targetDir, "docker-compose.yml");

  // Don't overwrite if it already exists from the template
  if (existsSync(dockerComposePath)) {
    return;
  }

  const content = `services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: keel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
`;

  writeFileSync(dockerComposePath, content, "utf-8");
}

/**
 * Clean up the sails/ folder in the scaffolded project.
 *
 * The template repo contains cli/sails/ (sail definitions for the CLI tool)
 * AND sails/ (minimal tracker for projects). After cloning, we ensure the
 * project's sails/ folder only has the clean tracker files, and remove the
 * cli/ directory entirely (it's part of the tooling, not the project).
 */
function cleanupSailsFolder(targetDir: string): void {
  const sailsDir = join(targetDir, "sails");

  // Ensure the sails directory exists with only the tracker
  mkdirSync(sailsDir, { recursive: true });

  // Write a clean installed.json
  const installedPath = join(sailsDir, "installed.json");
  writeFileSync(
    installedPath,
    JSON.stringify({ installed: [] }, null, 2) + "\n",
    "utf-8"
  );

  // Remove the cli/ directory from the scaffolded project (it's the tooling,
  // not part of the created project)
  const cliDir = join(targetDir, "cli");
  if (existsSync(cliDir)) {
    rmSync(cliDir, { recursive: true, force: true });
  }
}

/**
 * Scaffold a new project from the keel template.
 */
export async function scaffold(config: ProjectConfig): Promise<boolean> {
  const targetDir = resolve(process.cwd(), config.projectName);

  // -- Step 1: Clone template ------------------------------------------------
  const cloneSpinner = ora("Cloning template...").start();

  if (existsSync(targetDir)) {
    cloneSpinner.fail(`Directory already exists: ${config.projectName}`);
    return false;
  }

  try {
    const emitter = degit(TEMPLATE_REPO, {
      cache: false,
      force: true,
      verbose: false,
    });
    await emitter.clone(targetDir);
    cloneSpinner.succeed("Template cloned");
  } catch (error) {
    cloneSpinner.fail("Failed to clone template");
    console.error(chalk.red(`  ${error}`));
    return false;
  }

  // -- Step 2: Clean up sails and cli folders ---------------------------------
  const cleanupSpinner = ora("Preparing project structure...").start();
  try {
    cleanupSailsFolder(targetDir);
    cleanupSpinner.succeed("Project structure prepared");
  } catch (error) {
    cleanupSpinner.fail("Failed to prepare project structure");
    console.error(chalk.red(`  ${error}`));
  }

  // -- Step 3: Replace branding placeholders -----------------------------------
  const brandSpinner = ora("Customizing project...").start();

  try {
    // Replace package scope in all package.json files
    replaceInAllFiles(targetDir, /package\.json$/, "@keel", `@${config.projectName}`);

    // Replace project name in config files
    const configFiles = [
      "package.json",
      "packages/backend/package.json",
      "packages/frontend/package.json",
      "packages/shared/package.json",
      "packages/transactional/package.json",
      "docker-compose.yml",
      "docker-compose.prod.yml",
      "fly.toml",
    ];

    for (const file of configFiles) {
      replaceInFile(join(targetDir, file), "keel", config.projectName);
    }

    // Update Capacitor config
    const capConfigPath = join(targetDir, "packages/frontend/capacitor.config.ts");
    if (existsSync(capConfigPath)) {
      replaceInFile(capConfigPath, "com.keel.app", config.appId);
      replaceInFile(capConfigPath, "keel", config.displayName);
    }

    // Update the root package.json name and description
    const rootPkgPath = join(targetDir, "package.json");
    if (existsSync(rootPkgPath)) {
      const rootPkg = JSON.parse(readFileSync(rootPkgPath, "utf-8"));
      rootPkg.name = config.projectName;
      rootPkg.description = config.description;
      writeFileSync(rootPkgPath, JSON.stringify(rootPkg, null, 2) + "\n", "utf-8");
    }

    brandSpinner.succeed("Project customized");
  } catch (error) {
    brandSpinner.fail("Failed to customize project");
    console.error(chalk.red(`  ${error}`));
    return false;
  }

  // -- Step 4: Write .env file with collected values ---------------------------
  const envSpinner = ora("Writing environment configuration...").start();

  try {
    const envContents = buildEnvContents(config);
    const envPath = join(targetDir, ".env");
    const envExamplePath = join(targetDir, ".env.example");

    // Write .env with actual values
    writeFileSync(envPath, envContents, "utf-8");

    // Also update .env.example if it exists (keep template placeholders but add
    // any new vars that might be missing)
    if (existsSync(envExamplePath)) {
      let exampleContent = readFileSync(envExamplePath, "utf-8");

      // Ensure key variables exist in .env.example
      const keysToCheck = [
        ["DATABASE_URL", "postgresql://postgres:postgres@localhost:5432/keel"],
        ["BETTER_AUTH_SECRET", "your-secret-here"],
        ["RESEND_API_KEY", ""],
        ["EMAIL_FROM", "noreply@example.com"],
      ];

      for (const [key, placeholder] of keysToCheck) {
        if (!exampleContent.includes(key)) {
          exampleContent += `${key}=${placeholder}\n`;
        }
      }

      writeFileSync(envExamplePath, exampleContent, "utf-8");
    }

    envSpinner.succeed("Environment configuration written");
  } catch (error) {
    envSpinner.fail("Failed to write environment configuration");
    console.error(chalk.red(`  ${error}`));
  }

  // -- Step 5: Create docker-compose.yml if Docker was selected ----------------
  if (config.databaseSetup === "docker") {
    const dockerSpinner = ora("Creating docker-compose.yml...").start();
    try {
      createDockerCompose(targetDir);
      dockerSpinner.succeed("docker-compose.yml created");
    } catch (error) {
      dockerSpinner.fail("Failed to create docker-compose.yml");
      console.error(chalk.red(`  ${error}`));
    }
  }

  // -- Step 6: Install dependencies --------------------------------------------
  const installSpinner = ora("Installing dependencies (this may take a minute)...").start();

  try {
    execSync("npm install", { cwd: targetDir, stdio: "pipe", timeout: 300_000 });
    installSpinner.succeed("Dependencies installed");
  } catch (error) {
    installSpinner.fail("Failed to install dependencies");
    console.error(
      chalk.yellow("  You can try running 'npm install' manually in the project directory.")
    );
  }

  // -- Step 7: Add native platforms --------------------------------------------
  if (config.platforms !== "none") {
    const platformSpinner = ora("Adding native platforms...").start();

    const frontendDir = join(targetDir, "packages/frontend");

    try {
      if (config.platforms === "both" || config.platforms === "ios") {
        execSync("npx cap add ios", { cwd: frontendDir, stdio: "pipe" });
      }
      if (config.platforms === "both" || config.platforms === "android") {
        execSync("npx cap add android", { cwd: frontendDir, stdio: "pipe" });
      }
      platformSpinner.succeed(`Native platform(s) added: ${config.platforms}`);
    } catch {
      platformSpinner.warn(
        "Could not add native platforms. Run 'npx cap add ios/android' manually."
      );
    }
  }

  // -- Step 8: Initialize git --------------------------------------------------
  const gitSpinner = ora("Initializing git repository...").start();

  try {
    execSync("git init", { cwd: targetDir, stdio: "pipe" });
    execSync("git add -A", { cwd: targetDir, stdio: "pipe" });
    execSync('git commit -m "Initial commit from create-keel"', {
      cwd: targetDir,
      stdio: "pipe",
    });
    gitSpinner.succeed("Git repository initialized");
  } catch {
    gitSpinner.warn("Could not initialize git. Run 'git init' manually.");
  }

  // -- Print Getting Started guide ---------------------------------------------
  console.log();
  console.log(chalk.bold("  Getting Started"));
  console.log(chalk.bold("  ---------------"));
  console.log();

  let stepNum = 1;

  console.log(chalk.white(`  ${stepNum}. Navigate to your project:`));
  console.log(chalk.cyan(`     cd ${config.projectName}`));
  stepNum++;

  if (config.databaseSetup === "docker") {
    console.log();
    console.log(chalk.white(`  ${stepNum}. Start the database:`));
    console.log(chalk.cyan("     docker compose up -d"));
    stepNum++;
  }

  console.log();
  console.log(chalk.white(`  ${stepNum}. Run database migrations:`));
  console.log(chalk.cyan("     npm run db:migrate"));
  stepNum++;

  console.log();
  console.log(chalk.white(`  ${stepNum}. Start the development server:`));
  console.log(chalk.cyan("     npm run dev"));
  stepNum++;

  if (config.platforms !== "none") {
    console.log();
    console.log(chalk.white(`  ${stepNum}. Open native IDE (optional):`));
    if (config.platforms === "both" || config.platforms === "ios") {
      console.log(chalk.cyan("     npx cap open ios"));
    }
    if (config.platforms === "both" || config.platforms === "android") {
      console.log(chalk.cyan("     npx cap open android"));
    }
    stepNum++;
  }

  console.log();

  return true;
}
