/**
 * Scaffolding logic for create-keel (a codai project).
 *
 * Clones the template repository (without git history), customizes branding,
 * writes environment variables, optionally creates a docker-compose.yml,
 * installs dependencies, and initializes a fresh git repository.
 */

import {
  existsSync,
  readFileSync,
  writeFileSync,
  copyFileSync,
  mkdirSync,
  rmSync,
} from "node:fs";
import { join, resolve } from "node:path";
import { execFileSync } from "node:child_process";
import chalk from "chalk";
import ora from "ora";
import degit from "degit";

/** On Windows, bare "npm" must be invoked as "npm.cmd" for spawn/execFileSync. */
const NPM_CMD = process.platform === "win32" ? "npm.cmd" : "npm";
import type { ProjectConfig } from "./prompts.js";

const TEMPLATE_REPO = "Chafficui/keel";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function replaceInFile(filePath: string, search: string, replacement: string): void {
  if (!existsSync(filePath)) return;
  const content = readFileSync(filePath, "utf-8");
  if (!content.includes(search)) return;
  writeFileSync(filePath, content.replaceAll(search, replacement), "utf-8");
}

function buildEnvContents(config: ProjectConfig): string {
  const lines: string[] = [
    "# -------------------------------------------------------------------",
    `# Environment — ${config.projectName}`,
    "# Generated by create-keel",
    "# -------------------------------------------------------------------",
    "",
    "# Database",
    `DATABASE_URL=${config.databaseUrl}`,
    "",
    "# Auth",
    `BETTER_AUTH_SECRET=${config.betterAuthSecret}`,
    "",
    "# Server",
    "PORT=3005",
    `BACKEND_URL=http://localhost:3005`,
    `FRONTEND_URL=http://localhost:5173`,
    "",
    "# Email (Resend)",
    `RESEND_API_KEY=${config.resendApiKey}`,
    `EMAIL_FROM=${config.emailFrom}`,
    "",
  ];

  return lines.join("\n") + "\n";
}

function cleanupScaffold(targetDir: string): void {
  const sailsDir = join(targetDir, "sails");
  mkdirSync(sailsDir, { recursive: true });

  writeFileSync(
    join(sailsDir, "installed.json"),
    JSON.stringify({ installed: [] }, null, 2) + "\n",
    "utf-8"
  );

  // Remove files that belong to the keel tooling, not the consumer project
  const toRemove = ["cli", "brand", "README.md", "CLAUDE.md", ".claude"];
  for (const name of toRemove) {
    const fullPath = join(targetDir, name);
    if (existsSync(fullPath)) {
      rmSync(fullPath, { recursive: true, force: true });
    }
  }

  // Promote PROJECT_CLAUDE.md → CLAUDE.md (AI agent documentation for the project)
  const projectClaudeMd = join(targetDir, "PROJECT_CLAUDE.md");
  if (existsSync(projectClaudeMd)) {
    copyFileSync(projectClaudeMd, join(targetDir, "CLAUDE.md"));
    rmSync(projectClaudeMd);
  }
}

// ---------------------------------------------------------------------------
// Main scaffold
// ---------------------------------------------------------------------------

export async function scaffold(config: ProjectConfig): Promise<boolean> {
  const targetDir = resolve(process.cwd(), config.projectName);

  // -- Clone template --------------------------------------------------------
  const cloneSpinner = ora("Cloning template...").start();

  if (existsSync(targetDir)) {
    cloneSpinner.fail(`Directory already exists: ${config.projectName}`);
    return false;
  }

  try {
    let cloned = false;
    try {
      const emitter = degit(TEMPLATE_REPO, { cache: false, force: true, verbose: false });
      await emitter.clone(targetDir);
      cloned = true;
    } catch {
      // degit failed (private repo) — fall back to git clone
    }

    if (!cloned) {
      execFileSync("git", ["clone", "--depth", "1", `https://github.com/${TEMPLATE_REPO}.git`, targetDir], { stdio: "pipe" });
      rmSync(join(targetDir, ".git"), { recursive: true, force: true });
    }

    cloneSpinner.succeed("Template cloned");
  } catch (error) {
    cloneSpinner.fail("Failed to clone template");
    console.error(chalk.red(`  ${error}`));
    return false;
  }

  // -- Clean up tooling files ------------------------------------------------
  const cleanupSpinner = ora("Preparing project structure...").start();
  try {
    cleanupScaffold(targetDir);
    cleanupSpinner.succeed("Project structure prepared");
  } catch (error) {
    cleanupSpinner.fail("Failed to prepare project structure");
    console.error(chalk.red(`  ${error}`));
  }

  // -- Write project README --------------------------------------------------
  try {
    const readmeContent = `# ${config.displayName}

${config.description}

Built with [keel](https://github.com/Chafficui/keel) — a codai project.

## Quick Start

\`\`\`bash
# Start everything (database + migrations + dev servers)
keel dev
\`\`\`

Or manually:

\`\`\`bash
docker compose up -d          # Start PostgreSQL
npm run db:migrate             # Run database migrations
npm run dev                    # Start frontend + backend
\`\`\`

## Project Structure

\`\`\`
packages/
  shared/     — Shared types + validators
  email/      — Email templates (React Email)
  frontend/   — Vite + React + TypeScript SPA
  backend/    — Express + TypeScript API server
sails/        — Installed sail extensions
\`\`\`

## Useful Commands

| Command | Description |
|---------|-------------|
| \`keel dev\` | Start database, run migrations, launch dev servers |
| \`keel doctor\` | Health check (Node, Docker, DB, .env) |
| \`keel env\` | Show environment variable status |
| \`keel generate route <name>\` | Scaffold an API route |
| \`keel generate page <name>\` | Scaffold a React page |
| \`keel generate email <name>\` | Scaffold an email template |
| \`keel sail add <name>\` | Install a sail extension |
| \`keel list\` | Show available sails |
| \`keel db:studio\` | Open Drizzle Studio |
| \`keel db:reset\` | Reset database (destructive!) |

## Environment

Copy \`.env.example\` to \`.env\` and fill in the values. See \`keel env\` to check what's missing.

## Learn More

- [keel documentation](https://github.com/Chafficui/keel)
`;
    writeFileSync(join(targetDir, "README.md"), readmeContent, "utf-8");
  } catch (error) {
    console.error(chalk.yellow(`  Could not write README.md: ${error}`));
  }

  // -- Customize branding ----------------------------------------------------
  const brandSpinner = ora("Customizing project...").start();

  try {
    // Root package.json — name and description only
    const rootPkgPath = join(targetDir, "package.json");
    if (existsSync(rootPkgPath)) {
      const rootPkg = JSON.parse(readFileSync(rootPkgPath, "utf-8"));
      rootPkg.name = config.projectName;
      rootPkg.description = config.description;
      writeFileSync(rootPkgPath, JSON.stringify(rootPkg, null, 2) + "\n", "utf-8");
    }

    // Docker-compose DB name
    replaceInFile(
      join(targetDir, "docker-compose.yml"),
      "POSTGRES_DB: keel",
      `POSTGRES_DB: ${config.projectName}`
    );

    // Capacitor display name
    const capConfigPath = join(targetDir, "packages/frontend/capacitor.config.ts");
    if (existsSync(capConfigPath)) {
      replaceInFile(capConfigPath, 'appName: "Keel"', `appName: "${config.displayName}"`);
    }

    // Frontend env
    const frontendEnvPath = join(targetDir, "packages/frontend/.env");
    if (existsSync(frontendEnvPath)) {
      replaceInFile(frontendEnvPath, "VITE_APP_NAME=Keel", `VITE_APP_NAME=${config.displayName}`);
    }

    // Replace placeholders in static files (SEO, robots.txt, sitemap)
    const staticFiles = [
      join(targetDir, "packages/frontend/public/robots.txt"),
      join(targetDir, "packages/frontend/public/sitemap.xml"),
      join(targetDir, "packages/frontend/prerender.ts"),
    ];
    for (const filePath of staticFiles) {
      replaceInFile(filePath, "__APP_NAME__", config.displayName);
      replaceInFile(filePath, "__FRONTEND_URL__", "http://localhost:5173");
    }

    brandSpinner.succeed("Project customized");
  } catch (error) {
    brandSpinner.fail("Failed to customize project");
    console.error(chalk.red(`  ${error}`));
    return false;
  }

  // -- Write .env ------------------------------------------------------------
  const envSpinner = ora("Writing environment configuration...").start();

  try {
    writeFileSync(join(targetDir, ".env"), buildEnvContents(config), "utf-8");
    envSpinner.succeed("Environment configuration written");
  } catch (error) {
    envSpinner.fail("Failed to write environment configuration");
    console.error(chalk.red(`  ${error}`));
  }

  // -- PGlite data directory --------------------------------------------------
  // PGlite stores data relative to the backend CWD (packages/backend/)
  // because `npm run dev -w packages/backend` sets CWD there.
  if (config.databaseSetup === "pglite") {
    const dataDir = join(targetDir, "packages", "backend", "data", "pglite");
    mkdirSync(dataDir, { recursive: true });

    // Add data directories to .gitignore
    const gitignorePath = join(targetDir, ".gitignore");
    if (existsSync(gitignorePath)) {
      let gitignore = readFileSync(gitignorePath, "utf-8");
      if (!gitignore.includes("**/data/pglite")) {
        gitignore += "\n# PGlite local database\n**/data/pglite/\n";
        writeFileSync(gitignorePath, gitignore, "utf-8");
      }
    }
  }

  // -- Docker-compose --------------------------------------------------------
  if (config.databaseSetup === "docker") {
    // Template already ships with docker-compose.yml — only write if missing
    const dockerComposePath = join(targetDir, "docker-compose.yml");
    const content = `services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${config.projectName}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
`;
    try {
      writeFileSync(dockerComposePath, content, { encoding: "utf-8", flag: "wx" });
    } catch (error: unknown) {
      if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error;
      // File already exists (from template) — nothing to do
    }
  }

  // -- Install dependencies --------------------------------------------------
  const installSpinner = ora("Installing dependencies (this may take a minute)...").start();

  try {
    execFileSync(NPM_CMD, ["install"], { cwd: targetDir, stdio: "pipe", timeout: 300_000 });
    installSpinner.succeed("Dependencies installed");
  } catch (error) {
    installSpinner.fail("Failed to install dependencies");
    const msg = error instanceof Error ? error.message : String(error);
    console.error(chalk.yellow(`  ${msg}`));
    console.error(chalk.yellow("  Run 'npm install' manually in the project directory."));
  }

  // -- Initialize git --------------------------------------------------------
  const gitSpinner = ora("Initializing git repository...").start();

  try {
    execFileSync("git", ["init"], { cwd: targetDir, stdio: "pipe" });
    execFileSync("git", ["add", "-A"], { cwd: targetDir, stdio: "pipe" });
    execFileSync("git", ["commit", "-m", "Initial commit from create-keel"], {
      cwd: targetDir,
      stdio: "pipe",
    });
    gitSpinner.succeed("Git repository initialized");
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    gitSpinner.warn(`Could not initialize git: ${msg}`);
  }

  return true;
}
