/**
 * Scaffolding logic for create-keel (a codai project).
 *
 * Clones the template repository (without git history), customizes branding,
 * writes environment variables, optionally creates a docker-compose.yml,
 * installs dependencies, and initializes a fresh git repository.
 */

import {
  existsSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  rmSync,
} from "node:fs";
import { join, resolve } from "node:path";
import { execSync } from "node:child_process";
import chalk from "chalk";
import ora from "ora";
import degit from "degit";
import type { ProjectConfig } from "./prompts.js";

const TEMPLATE_REPO = "Chafficui/keel";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function replaceInFile(filePath: string, search: string, replacement: string): void {
  if (!existsSync(filePath)) return;
  const content = readFileSync(filePath, "utf-8");
  if (!content.includes(search)) return;
  writeFileSync(filePath, content.replaceAll(search, replacement), "utf-8");
}

function buildEnvContents(config: ProjectConfig): string {
  const lines: string[] = [
    "# -------------------------------------------------------------------",
    `# Environment — ${config.projectName}`,
    "# Generated by create-keel",
    "# -------------------------------------------------------------------",
    "",
    "# Database",
    `DATABASE_URL=${config.databaseUrl}`,
    "",
    "# Auth",
    `BETTER_AUTH_SECRET=${config.betterAuthSecret}`,
    "",
    "# Server",
    "PORT=3005",
    `BACKEND_URL=http://localhost:3005`,
    `FRONTEND_URL=http://localhost:5173`,
    "",
    "# Email (Resend)",
    `RESEND_API_KEY=${config.resendApiKey}`,
    `EMAIL_FROM=${config.emailFrom}`,
    "",
  ];

  return lines.join("\n") + "\n";
}

function cleanupScaffold(targetDir: string): void {
  const sailsDir = join(targetDir, "sails");
  mkdirSync(sailsDir, { recursive: true });

  writeFileSync(
    join(sailsDir, "installed.json"),
    JSON.stringify({ installed: [] }, null, 2) + "\n",
    "utf-8"
  );

  // Remove files that belong to the keel tooling, not the consumer project
  const toRemove = ["cli", "brand", "README.md", "CLAUDE.md", ".claude"];
  for (const name of toRemove) {
    const fullPath = join(targetDir, name);
    if (existsSync(fullPath)) {
      rmSync(fullPath, { recursive: true, force: true });
    }
  }
}

// ---------------------------------------------------------------------------
// Main scaffold
// ---------------------------------------------------------------------------

export async function scaffold(config: ProjectConfig): Promise<boolean> {
  const targetDir = resolve(process.cwd(), config.projectName);

  // -- Clone template --------------------------------------------------------
  const cloneSpinner = ora("Cloning template...").start();

  if (existsSync(targetDir)) {
    cloneSpinner.fail(`Directory already exists: ${config.projectName}`);
    return false;
  }

  try {
    let cloned = false;
    try {
      const emitter = degit(TEMPLATE_REPO, { cache: false, force: true, verbose: false });
      await emitter.clone(targetDir);
      cloned = true;
    } catch {
      // degit failed (private repo) — fall back to git clone
    }

    if (!cloned) {
      execSync(
        `git clone --depth 1 https://github.com/${TEMPLATE_REPO}.git "${targetDir}"`,
        { stdio: "pipe" }
      );
      rmSync(join(targetDir, ".git"), { recursive: true, force: true });
    }

    cloneSpinner.succeed("Template cloned");
  } catch (error) {
    cloneSpinner.fail("Failed to clone template");
    console.error(chalk.red(`  ${error}`));
    return false;
  }

  // -- Clean up tooling files ------------------------------------------------
  const cleanupSpinner = ora("Preparing project structure...").start();
  try {
    cleanupScaffold(targetDir);
    cleanupSpinner.succeed("Project structure prepared");
  } catch (error) {
    cleanupSpinner.fail("Failed to prepare project structure");
    console.error(chalk.red(`  ${error}`));
  }

  // -- Customize branding ----------------------------------------------------
  const brandSpinner = ora("Customizing project...").start();

  try {
    // Root package.json — name and description only
    const rootPkgPath = join(targetDir, "package.json");
    if (existsSync(rootPkgPath)) {
      const rootPkg = JSON.parse(readFileSync(rootPkgPath, "utf-8"));
      rootPkg.name = config.projectName;
      rootPkg.description = config.description;
      writeFileSync(rootPkgPath, JSON.stringify(rootPkg, null, 2) + "\n", "utf-8");
    }

    // Docker-compose DB name
    replaceInFile(
      join(targetDir, "docker-compose.yml"),
      "POSTGRES_DB: keel",
      `POSTGRES_DB: ${config.projectName}`
    );

    // Capacitor display name
    const capConfigPath = join(targetDir, "packages/frontend/capacitor.config.ts");
    if (existsSync(capConfigPath)) {
      replaceInFile(capConfigPath, 'appName: "Keel"', `appName: "${config.displayName}"`);
    }

    // Frontend env
    const frontendEnvPath = join(targetDir, "packages/frontend/.env");
    if (existsSync(frontendEnvPath)) {
      replaceInFile(frontendEnvPath, "VITE_APP_NAME=Keel", `VITE_APP_NAME=${config.displayName}`);
    }

    brandSpinner.succeed("Project customized");
  } catch (error) {
    brandSpinner.fail("Failed to customize project");
    console.error(chalk.red(`  ${error}`));
    return false;
  }

  // -- Write .env ------------------------------------------------------------
  const envSpinner = ora("Writing environment configuration...").start();

  try {
    writeFileSync(join(targetDir, ".env"), buildEnvContents(config), "utf-8");
    envSpinner.succeed("Environment configuration written");
  } catch (error) {
    envSpinner.fail("Failed to write environment configuration");
    console.error(chalk.red(`  ${error}`));
  }

  // -- Docker-compose --------------------------------------------------------
  if (config.databaseSetup === "docker") {
    // Template already ships with docker-compose.yml — just confirm it exists
    if (!existsSync(join(targetDir, "docker-compose.yml"))) {
      const content = `services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${config.projectName}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
`;
      writeFileSync(join(targetDir, "docker-compose.yml"), content, "utf-8");
    }
  }

  // -- Install dependencies --------------------------------------------------
  const installSpinner = ora("Installing dependencies (this may take a minute)...").start();

  try {
    execSync("npm install", { cwd: targetDir, stdio: "pipe", timeout: 300_000 });
    installSpinner.succeed("Dependencies installed");
  } catch {
    installSpinner.fail("Failed to install dependencies");
    console.error(chalk.yellow("  Run 'npm install' manually in the project directory."));
  }

  // -- Initialize git --------------------------------------------------------
  const gitSpinner = ora("Initializing git repository...").start();

  try {
    execSync("git init", { cwd: targetDir, stdio: "pipe" });
    execSync("git add -A", { cwd: targetDir, stdio: "pipe" });
    execSync('git commit -m "Initial commit from create-keel"', {
      cwd: targetDir,
      stdio: "pipe",
    });
    gitSpinner.succeed("Git repository initialized");
  } catch {
    gitSpinner.warn("Could not initialize git. Run 'git init' manually.");
  }

  return true;
}
